services:
  mysql:
    image: 'mysql:8-oracle'
    environment:
      - 'MYSQL_DATABASE=social-media-database'
      - 'MYSQL_PASSWORD=social-media-user'
      - 'MYSQL_ROOT_PASSWORD=dummypassword'
      - 'MYSQL_USER=social-media-user'
    ports:
      - '3306'
#    volumes:
#      - /usr/sbin/mysqld

#lab-exericise-909:
#  container-name: lab-exercise-909
#  build:
#    context: ./
#    dockerfile: Dockerfile
#  ports:
#    - "8092:8092"
#  depends_on:
#    - mysql
#  restart: on-failure


